spring:
  profiles:
    active: live
  cloud:
    stream:
      default:
        group: messages
        producer:
          requiredGroups: statistic, ui
      instance-count: 2

---
spring:
  profiles: live
  cloud:
    stream:
      instance-index: 0
---
spring:
  profiles: replica
  cloud:
    stream:
      instance-index: 1